//! GF(2^16) arithmetic for PAR2 Reed-Solomon repair.
//!
//! The PAR2 field: GF(65536) generated by x^16 + x^12 + x^3 + x + 1
//! (0x1100B), with 2 as the primitive element - the same field
//! par2cmdline uses, so recovery data interoperates bit-for-bit.
//!
//! Everything routes through one pair of log/exp tables (built once,
//! 512 KB). Buffer-scale work - "dst ^= c · src over u16 words" - uses
//! the classic split-table trick: a 256-entry table for each byte half
//! of the word turns a full GF multiply into two lookups and an XOR.

use std::sync::OnceLock;

/// The PAR2 generator polynomial (bit 16 implied).
const POLY: u32 = 0x1100B;
/// Order of the multiplicative group (2^16 − 1).
pub const ORDER: u32 = 65535;

struct Tables {
    /// exp[i] = 2^i; doubled to 2·ORDER entries so `log a + log b` and
    /// `ORDER − log a` index without a modulo.
    exp: Vec<u16>,
    /// log[a] = i with 2^i = a, for a ≠ 0. log[0] is unused (0 has no log).
    log: Vec<u16>,
}

fn tables() -> &'static Tables {
    static TABLES: OnceLock<Tables> = OnceLock::new();
    TABLES.get_or_init(|| {
        let mut exp = vec![0u16; ORDER as usize * 2];
        let mut log = vec![0u16; 65536];
        let mut v: u32 = 1;
        for i in 0..ORDER as usize {
            exp[i] = v as u16;
            log[v as usize] = i as u16;
            v <<= 1;
            if v & 0x1_0000 != 0 {
                v ^= POLY;
            }
        }
        debug_assert_eq!(v, 1, "2 must have full order {ORDER}");
        for i in 0..ORDER as usize {
            exp[ORDER as usize + i] = exp[i];
        }
        Tables { exp, log }
    })
}

pub fn mul(a: u16, b: u16) -> u16 {
    if a == 0 || b == 0 {
        return 0;
    }
    let t = tables();
    t.exp[t.log[a as usize] as usize + t.log[b as usize] as usize]
}

/// 2^e with e reduced mod ORDER - every PAR2 RS matrix entry is one of
/// these: input slice i's base is 2^{k_i}, so base^exponent = 2^{k_i·e}.
pub fn pow2(e: u64) -> u16 {
    tables().exp[(e % ORDER as u64) as usize]
}

/// Multiplicative inverse. `a` must be non-zero.
pub fn inv(a: u16) -> u16 {
    debug_assert_ne!(a, 0, "0 has no inverse");
    let t = tables();
    t.exp[(ORDER - t.log[a as usize] as u32) as usize]
}

/// Split-multiply table for one scalar `c`: word × c via two byte lookups
/// (scalar), plus 4-bit nibble tables for the SIMD fold paths (NEON on
/// aarch64, SSSE3/AVX2 on x86_64).
pub struct MulTable {
    lo: [u16; 256],
    hi: [u16; 256],
    /// SIMD nibble tables: `nl[j][n]`/`nh[j][n]` are the low/high byte of
    /// `c · (n << 4j)` for nibble `n` - a u16 word's product is the XOR of
    /// its four nibbles' contributions, each a single 16-byte table shuffle
    /// (`vqtbl1q_u8` on NEON, `pshufb` on x86).
    #[cfg(any(target_arch = "aarch64", target_arch = "x86_64"))]
    nl: [[u8; 16]; 4],
    #[cfg(any(target_arch = "aarch64", target_arch = "x86_64"))]
    nh: [[u8; 16]; 4],
    /// GFNI 8x8 bit-matrices `[ll, hl, lh, hh]`: multiply-by-c over
    /// GF(2^16) is GF(2)-linear, so it splits into four byte→byte maps
    /// (product low/high byte from source low/high byte), each one
    /// `gf2p8affineqb` - the whole word product costs 4 affines where
    /// the nibble path needs 8 shuffles plus the nibble extraction.
    #[cfg(target_arch = "x86_64")]
    affine: [u64; 4],
}

/// Pack the byte→byte GF(2) linear map `j → take(products[j])` into the
/// `gf2p8affineqb` matrix operand: destination bit `i`'s row lives in
/// qword byte `7 − i`, and bit `j` of a row selects source bit `j`.
#[cfg(target_arch = "x86_64")]
fn affine_matrix(products: &[u16; 8], take: fn(u16) -> u8) -> u64 {
    let mut m = 0u64;
    for i in 0..8 {
        let mut row = 0u8;
        for (j, &p) in products.iter().enumerate() {
            row |= ((take(p) >> i) & 1) << j;
        }
        m |= (row as u64) << (8 * (7 - i));
    }
    m
}

impl MulTable {
    pub fn new(c: u16) -> MulTable {
        let mut lo = [0u16; 256];
        let mut hi = [0u16; 256];
        for b in 0..256u16 {
            lo[b as usize] = mul(c, b);
            hi[b as usize] = mul(c, b << 8);
        }
        #[cfg(any(target_arch = "aarch64", target_arch = "x86_64"))]
        let (nl, nh) = {
            let mut nl = [[0u8; 16]; 4];
            let mut nh = [[0u8; 16]; 4];
            for (j, (nlj, nhj)) in nl.iter_mut().zip(nh.iter_mut()).enumerate() {
                for n in 0..16u16 {
                    let p = mul(c, n << (4 * j));
                    nlj[n as usize] = p as u8;
                    nhj[n as usize] = (p >> 8) as u8;
                }
            }
            (nl, nh)
        };
        #[cfg(target_arch = "x86_64")]
        let affine = {
            let mut lo_basis = [0u16; 8];
            let mut hi_basis = [0u16; 8];
            for j in 0..8 {
                lo_basis[j] = mul(c, 1 << j);
                hi_basis[j] = mul(c, 1 << (8 + j));
            }
            [
                affine_matrix(&lo_basis, |p| p as u8),
                affine_matrix(&hi_basis, |p| p as u8),
                affine_matrix(&lo_basis, |p| (p >> 8) as u8),
                affine_matrix(&hi_basis, |p| (p >> 8) as u8),
            ]
        };
        MulTable {
            lo,
            hi,
            #[cfg(any(target_arch = "aarch64", target_arch = "x86_64"))]
            nl,
            #[cfg(any(target_arch = "aarch64", target_arch = "x86_64"))]
            nh,
            #[cfg(target_arch = "x86_64")]
            affine,
        }
    }

    #[inline]
    pub fn mul(&self, w: u16) -> u16 {
        self.lo[(w & 0xff) as usize] ^ self.hi[(w >> 8) as usize]
    }

    /// dst ^= c · src, with `src` raw little-endian bytes and `dst` u16
    /// words. `src` may be shorter than `dst` - PAR2 zero-pads tail
    /// slices, and c·0 contributes nothing, so short input just stops
    /// early. An odd trailing byte is the low half of a final word.
    ///
    /// This is the PAR2 repair fold hotspot (one call per syndrome-row ×
    /// present-slice, over whole blocks). On aarch64 the bulk runs on
    /// NEON - 16 words per iteration via nibble-table `vqtbl` lookups -
    /// and on x86_64 on AVX2 (32 words/iter) or SSSE3 (16), picked at
    /// runtime; the scalar path (below) handles the short tail.
    pub fn xor_mul_into(&self, dst: &mut [u16], src: &[u8]) {
        assert!(src.len().div_ceil(2) <= dst.len(), "src longer than dst");
        #[cfg(target_arch = "aarch64")]
        let done = unsafe { self.xor_mul_into_neon(dst, src) };
        #[cfg(target_arch = "x86_64")]
        let done = if is_x86_feature_detected!("gfni") && is_x86_feature_detected!("avx2") {
            unsafe { self.xor_mul_into_gfni(dst, src) }
        } else if is_x86_feature_detected!("avx2") {
            unsafe { self.xor_mul_into_avx2(dst, src) }
        } else if is_x86_feature_detected!("ssse3") {
            unsafe { self.xor_mul_into_ssse3(dst, src) }
        } else {
            0usize
        };
        #[cfg(not(any(target_arch = "aarch64", target_arch = "x86_64")))]
        let done = 0usize;
        Self::xor_mul_scalar(&self.lo, &self.hi, &mut dst[done..], &src[done * 2..]);
    }

    /// Scalar fold (the whole op off aarch64; the tail on it). Also the
    /// differential oracle for the NEON path.
    fn xor_mul_scalar(lo: &[u16; 256], hi: &[u16; 256], dst: &mut [u16], src: &[u8]) {
        let words = src.len() / 2;
        for (d, s) in dst.iter_mut().zip(src.chunks_exact(2)) {
            *d ^= lo[s[0] as usize] ^ hi[s[1] as usize];
        }
        if src.len() % 2 == 1 {
            dst[words] ^= lo[src[src.len() - 1] as usize];
        }
    }

    /// NEON fold: `dst[i] ^= c · src_word[i]` for whole 32-byte (16-word)
    /// chunks. Returns the number of u16 WORDS processed; the caller runs
    /// the remainder scalar. NEON is baseline on aarch64, so no runtime
    /// feature check is needed.
    #[cfg(target_arch = "aarch64")]
    unsafe fn xor_mul_into_neon(&self, dst: &mut [u16], src: &[u8]) -> usize {
        use std::arch::aarch64::*;
        let chunks = src.len() / 32;
        if chunks == 0 {
            return 0;
        }
        unsafe {
            let (t0l, t1l, t2l, t3l) = (
                vld1q_u8(self.nl[0].as_ptr()),
                vld1q_u8(self.nl[1].as_ptr()),
                vld1q_u8(self.nl[2].as_ptr()),
                vld1q_u8(self.nl[3].as_ptr()),
            );
            let (t0h, t1h, t2h, t3h) = (
                vld1q_u8(self.nh[0].as_ptr()),
                vld1q_u8(self.nh[1].as_ptr()),
                vld1q_u8(self.nh[2].as_ptr()),
                vld1q_u8(self.nh[3].as_ptr()),
            );
            let mask = vdupq_n_u8(0x0f);
            let dst_bytes = dst.as_mut_ptr() as *mut u8;
            for c in 0..chunks {
                // src bytes deinterleave to low/high bytes of the 16 words.
                let s = vld2q_u8(src.as_ptr().add(c * 32));
                let n0 = vandq_u8(s.0, mask);
                let n1 = vshrq_n_u8::<4>(s.0);
                let n2 = vandq_u8(s.1, mask);
                let n3 = vshrq_n_u8::<4>(s.1);
                let plo = veorq_u8(
                    veorq_u8(vqtbl1q_u8(t0l, n0), vqtbl1q_u8(t1l, n1)),
                    veorq_u8(vqtbl1q_u8(t2l, n2), vqtbl1q_u8(t3l, n3)),
                );
                let phi = veorq_u8(
                    veorq_u8(vqtbl1q_u8(t0h, n0), vqtbl1q_u8(t1h, n1)),
                    veorq_u8(vqtbl1q_u8(t2h, n2), vqtbl1q_u8(t3h, n3)),
                );
                let dp = dst_bytes.add(c * 32);
                let d = vld2q_u8(dp);
                vst2q_u8(dp, uint8x16x2_t(veorq_u8(d.0, plo), veorq_u8(d.1, phi)));
            }
        }
        chunks * 16
    }

    /// SSSE3 fold: the `pshufb` twin of the NEON path - same nibble
    /// tables, 16 words per 32-byte chunk. x86 has no deinterleaving
    /// load, so low/high bytes are split with mask+`packus` and the
    /// products re-interleaved with `unpack` before XORing into `dst`
    /// in place. Returns the number of u16 WORDS processed; the caller
    /// runs the remainder scalar. Caller must have verified SSSE3.
    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "ssse3")]
    unsafe fn xor_mul_into_ssse3(&self, dst: &mut [u16], src: &[u8]) -> usize {
        use std::arch::x86_64::*;
        let chunks = src.len() / 32;
        if chunks == 0 {
            return 0;
        }
        unsafe {
            let (t0l, t1l, t2l, t3l) = (
                _mm_loadu_si128(self.nl[0].as_ptr() as *const __m128i),
                _mm_loadu_si128(self.nl[1].as_ptr() as *const __m128i),
                _mm_loadu_si128(self.nl[2].as_ptr() as *const __m128i),
                _mm_loadu_si128(self.nl[3].as_ptr() as *const __m128i),
            );
            let (t0h, t1h, t2h, t3h) = (
                _mm_loadu_si128(self.nh[0].as_ptr() as *const __m128i),
                _mm_loadu_si128(self.nh[1].as_ptr() as *const __m128i),
                _mm_loadu_si128(self.nh[2].as_ptr() as *const __m128i),
                _mm_loadu_si128(self.nh[3].as_ptr() as *const __m128i),
            );
            let nib = _mm_set1_epi8(0x0f);
            let lo8 = _mm_set1_epi16(0x00ff);
            let dst_bytes = dst.as_mut_ptr() as *mut u8;
            for c in 0..chunks {
                let sp = src.as_ptr().add(c * 32) as *const __m128i;
                let v0 = _mm_loadu_si128(sp);
                let v1 = _mm_loadu_si128(sp.add(1));
                // Split the 16 words into their low and high bytes.
                let slo = _mm_packus_epi16(_mm_and_si128(v0, lo8), _mm_and_si128(v1, lo8));
                let shi = _mm_packus_epi16(_mm_srli_epi16(v0, 8), _mm_srli_epi16(v1, 8));
                let n0 = _mm_and_si128(slo, nib);
                let n1 = _mm_and_si128(_mm_srli_epi16(slo, 4), nib);
                let n2 = _mm_and_si128(shi, nib);
                let n3 = _mm_and_si128(_mm_srli_epi16(shi, 4), nib);
                let plo = _mm_xor_si128(
                    _mm_xor_si128(_mm_shuffle_epi8(t0l, n0), _mm_shuffle_epi8(t1l, n1)),
                    _mm_xor_si128(_mm_shuffle_epi8(t2l, n2), _mm_shuffle_epi8(t3l, n3)),
                );
                let phi = _mm_xor_si128(
                    _mm_xor_si128(_mm_shuffle_epi8(t0h, n0), _mm_shuffle_epi8(t1h, n1)),
                    _mm_xor_si128(_mm_shuffle_epi8(t2h, n2), _mm_shuffle_epi8(t3h, n3)),
                );
                // Re-interleave the product bytes into word order; the XOR
                // into dst then needs no deinterleave at all.
                let dp = dst_bytes.add(c * 32) as *mut __m128i;
                let d0 = _mm_loadu_si128(dp);
                let d1 = _mm_loadu_si128(dp.add(1));
                _mm_storeu_si128(dp, _mm_xor_si128(d0, _mm_unpacklo_epi8(plo, phi)));
                _mm_storeu_si128(dp.add(1), _mm_xor_si128(d1, _mm_unpackhi_epi8(plo, phi)));
            }
        }
        chunks * 16
    }

    /// AVX2 fold: the SSSE3 path widened to 32 words per 64-byte chunk -
    /// `vpshufb` shuffles each 128-bit lane against its own copy of the
    /// broadcast nibble table, and `packus`/`unpack` are lane-local too,
    /// so the split/lookup/re-interleave round-trips within each lane
    /// exactly as in the 128-bit version. Returns u16 WORDS processed;
    /// caller runs the remainder scalar. Caller must have verified AVX2.
    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "avx2")]
    unsafe fn xor_mul_into_avx2(&self, dst: &mut [u16], src: &[u8]) -> usize {
        use std::arch::x86_64::*;
        let chunks = src.len() / 64;
        if chunks == 0 {
            return 0;
        }
        unsafe {
            let bc = |t: &[u8; 16]| {
                _mm256_broadcastsi128_si256(_mm_loadu_si128(t.as_ptr() as *const __m128i))
            };
            let (t0l, t1l, t2l, t3l) = (
                bc(&self.nl[0]),
                bc(&self.nl[1]),
                bc(&self.nl[2]),
                bc(&self.nl[3]),
            );
            let (t0h, t1h, t2h, t3h) = (
                bc(&self.nh[0]),
                bc(&self.nh[1]),
                bc(&self.nh[2]),
                bc(&self.nh[3]),
            );
            let nib = _mm256_set1_epi8(0x0f);
            let lo8 = _mm256_set1_epi16(0x00ff);
            let dst_bytes = dst.as_mut_ptr() as *mut u8;
            for c in 0..chunks {
                let sp = src.as_ptr().add(c * 64) as *const __m256i;
                let v0 = _mm256_loadu_si256(sp);
                let v1 = _mm256_loadu_si256(sp.add(1));
                let slo = _mm256_packus_epi16(_mm256_and_si256(v0, lo8), _mm256_and_si256(v1, lo8));
                let shi = _mm256_packus_epi16(_mm256_srli_epi16(v0, 8), _mm256_srli_epi16(v1, 8));
                let n0 = _mm256_and_si256(slo, nib);
                let n1 = _mm256_and_si256(_mm256_srli_epi16(slo, 4), nib);
                let n2 = _mm256_and_si256(shi, nib);
                let n3 = _mm256_and_si256(_mm256_srli_epi16(shi, 4), nib);
                let plo = _mm256_xor_si256(
                    _mm256_xor_si256(_mm256_shuffle_epi8(t0l, n0), _mm256_shuffle_epi8(t1l, n1)),
                    _mm256_xor_si256(_mm256_shuffle_epi8(t2l, n2), _mm256_shuffle_epi8(t3l, n3)),
                );
                let phi = _mm256_xor_si256(
                    _mm256_xor_si256(_mm256_shuffle_epi8(t0h, n0), _mm256_shuffle_epi8(t1h, n1)),
                    _mm256_xor_si256(_mm256_shuffle_epi8(t2h, n2), _mm256_shuffle_epi8(t3h, n3)),
                );
                let dp = dst_bytes.add(c * 64) as *mut __m256i;
                let d0 = _mm256_loadu_si256(dp);
                let d1 = _mm256_loadu_si256(dp.add(1));
                _mm256_storeu_si256(dp, _mm256_xor_si256(d0, _mm256_unpacklo_epi8(plo, phi)));
                _mm256_storeu_si256(
                    dp.add(1),
                    _mm256_xor_si256(d1, _mm256_unpackhi_epi8(plo, phi)),
                );
            }
        }
        chunks * 32
    }

    /// GFNI+AVX2 fold: the AVX2 nibble path with the 8 table shuffles
    /// replaced by 4 `gf2p8affineqb`s against the four 8x8 bit-matrices
    /// in `self.affine` (see the field docs) - same split/re-interleave
    /// framing, half the shuffle-port traffic and no nibble extraction.
    /// Returns u16 WORDS processed; caller runs the remainder scalar.
    /// Caller must have verified GFNI and AVX2.
    #[cfg(target_arch = "x86_64")]
    #[target_feature(enable = "gfni,avx2")]
    unsafe fn xor_mul_into_gfni(&self, dst: &mut [u16], src: &[u8]) -> usize {
        use std::arch::x86_64::*;
        let chunks = src.len() / 64;
        if chunks == 0 {
            return 0;
        }
        unsafe {
            let mll = _mm256_set1_epi64x(self.affine[0] as i64);
            let mhl = _mm256_set1_epi64x(self.affine[1] as i64);
            let mlh = _mm256_set1_epi64x(self.affine[2] as i64);
            let mhh = _mm256_set1_epi64x(self.affine[3] as i64);
            let lo8 = _mm256_set1_epi16(0x00ff);
            let dst_bytes = dst.as_mut_ptr() as *mut u8;
            for c in 0..chunks {
                let sp = src.as_ptr().add(c * 64) as *const __m256i;
                let v0 = _mm256_loadu_si256(sp);
                let v1 = _mm256_loadu_si256(sp.add(1));
                let slo = _mm256_packus_epi16(_mm256_and_si256(v0, lo8), _mm256_and_si256(v1, lo8));
                let shi = _mm256_packus_epi16(_mm256_srli_epi16(v0, 8), _mm256_srli_epi16(v1, 8));
                let plo = _mm256_xor_si256(
                    _mm256_gf2p8affine_epi64_epi8::<0>(slo, mll),
                    _mm256_gf2p8affine_epi64_epi8::<0>(shi, mhl),
                );
                let phi = _mm256_xor_si256(
                    _mm256_gf2p8affine_epi64_epi8::<0>(slo, mlh),
                    _mm256_gf2p8affine_epi64_epi8::<0>(shi, mhh),
                );
                let dp = dst_bytes.add(c * 64) as *mut __m256i;
                let d0 = _mm256_loadu_si256(dp);
                let d1 = _mm256_loadu_si256(dp.add(1));
                _mm256_storeu_si256(dp, _mm256_xor_si256(d0, _mm256_unpacklo_epi8(plo, phi)));
                _mm256_storeu_si256(
                    dp.add(1),
                    _mm256_xor_si256(d1, _mm256_unpackhi_epi8(plo, phi)),
                );
            }
        }
        chunks * 32
    }

    /// dst ^= c · src over u16 word slices (used by matrix row ops and
    /// the repair back-substitution). On little-endian targets the word
    /// slice IS its PAR2 byte representation, so this rides the same
    /// SIMD fold as [`xor_mul_into`](Self::xor_mul_into).
    pub fn xor_mul_words(&self, dst: &mut [u16], src: &[u16]) {
        #[cfg(target_endian = "little")]
        {
            let n = src.len().min(dst.len());
            self.xor_mul_into(&mut dst[..n], words_as_bytes(&src[..n]));
        }
        #[cfg(target_endian = "big")]
        for (d, s) in dst.iter_mut().zip(src) {
            *d ^= self.mul(*s);
        }
    }
}

/// View a u16 word slice as its PAR2 wire bytes. PAR2 reads slices as
/// little-endian words, so on the LE targets we ship this is a free
/// cast. (A big-endian port would need a byte-swapping copy instead -
/// hence the cfg, which makes any such port fail loudly at build time.)
#[cfg(target_endian = "little")]
pub fn words_as_bytes(w: &[u16]) -> &[u8] {
    // SAFETY: u16 has no padding or invalid bit patterns, and the cast
    // only narrows alignment.
    unsafe { std::slice::from_raw_parts(w.as_ptr().cast(), w.len() * 2) }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn known_values() {
        // 2^16 mod the generator polynomial: 0x1100B with bit 16 dropped.
        assert_eq!(pow2(16), 0x100B);
        assert_eq!(pow2(0), 1);
        assert_eq!(pow2(1), 2);
        // Full cycle wraps to 1.
        assert_eq!(pow2(ORDER as u64), 1);
    }

    #[test]
    fn field_axioms_sampled() {
        let xs = [1u16, 2, 3, 0x100B, 0x8000, 0xFFFF, 12345];
        for &a in &xs {
            assert_eq!(mul(a, 1), a);
            assert_eq!(mul(a, 0), 0);
            assert_eq!(mul(a, inv(a)), 1, "a·a⁻¹ = 1 for {a:#x}");
            for &b in &xs {
                assert_eq!(mul(a, b), mul(b, a));
                for &c in &xs {
                    assert_eq!(mul(a, mul(b, c)), mul(mul(a, b), c));
                    // Distributivity over XOR (field addition).
                    assert_eq!(mul(a, b ^ c), mul(a, b) ^ mul(a, c));
                }
            }
        }
    }

    #[test]
    fn mul_table_matches_scalar_mul() {
        for c in [0u16, 1, 2, 0x1234, 0xFFFF] {
            let t = MulTable::new(c);
            for w in [0u16, 1, 0xFF, 0x100, 0xABCD, 0xFFFF] {
                assert_eq!(t.mul(w), mul(c, w), "c={c:#x} w={w:#x}");
            }
        }
    }

    #[test]
    fn xor_mul_words_matches_per_word_mul() {
        let mut state = 0x243F6A8885A308D3u64;
        let mut rng = || {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state
        };
        for c in [0u16, 1, 2, 0x1234, 0xABCD, 0xFFFF] {
            let t = MulTable::new(c);
            for len in [0usize, 1, 15, 16, 17, 64, 4097] {
                let src: Vec<u16> = (0..len).map(|_| rng() as u16).collect();
                let base: Vec<u16> = (0..len).map(|_| rng() as u16).collect();
                let mut want = base.clone();
                for (d, s) in want.iter_mut().zip(&src) {
                    *d ^= mul(c, *s);
                }
                let mut got = base.clone();
                t.xor_mul_words(&mut got, &src);
                assert_eq!(got, want, "c={c:#x} len={len}");
            }
        }
    }

    #[test]
    fn xor_mul_into_handles_short_and_odd_src() {
        let c = 0x1234u16;
        let t = MulTable::new(c);
        let src = [1u8, 2, 3, 4, 5]; // odd length: last word is 0x0005
        let mut dst = vec![0u16; 4];
        t.xor_mul_into(&mut dst, &src);
        assert_eq!(dst[0], mul(c, u16::from_le_bytes([1, 2])));
        assert_eq!(dst[1], mul(c, u16::from_le_bytes([3, 4])));
        assert_eq!(dst[2], mul(c, 5));
        assert_eq!(dst[3], 0, "beyond src stays untouched (zero pad)");
    }

    /// `xor_mul_into` must match a straight per-word GF multiply for every
    /// length across, and just past, the NEON 32-byte chunk boundary and
    /// odd tails - on aarch64 this is the NEON path vs a scalar oracle,
    /// with a non-zero starting `dst` so the accumulate (`^=`) is exercised.
    #[test]
    fn xor_mul_into_matches_scalar_all_lengths() {
        let mut state = 0x9E3779B97F4A7C15u64;
        let mut rng = || {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            state
        };
        for c in [0u16, 1, 2, 0x00FF, 0x0101, 0x1234, 0xABCD, 0xFFFF] {
            let t = MulTable::new(c);
            for len in [0usize, 1, 2, 3, 15, 16, 31, 32, 33, 64, 65, 127, 4096, 4097] {
                let src: Vec<u8> = (0..len).map(|_| rng() as u8).collect();
                let words = len.div_ceil(2);
                let base: Vec<u16> = (0..words + 3).map(|_| rng() as u16).collect();
                // Oracle: start from `base`, add c·word per src word.
                let mut want = base.clone();
                for (i, s) in src.chunks(2).enumerate() {
                    let w = if s.len() == 2 {
                        u16::from_le_bytes([s[0], s[1]])
                    } else {
                        s[0] as u16
                    };
                    want[i] ^= mul(c, w);
                }
                let mut got = base.clone();
                t.xor_mul_into(&mut got, &src);
                assert_eq!(got, want, "c={c:#x} len={len}");

                // On x86_64 also drive each kernel directly - runtime
                // dispatch would only ever exercise the best one the CPU
                // has (e.g. AVX2 shadowing SSSE3).
                #[cfg(target_arch = "x86_64")]
                {
                    if is_x86_feature_detected!("ssse3") {
                        let mut got = base.clone();
                        let done = unsafe { t.xor_mul_into_ssse3(&mut got, &src) };
                        MulTable::xor_mul_scalar(&t.lo, &t.hi, &mut got[done..], &src[done * 2..]);
                        assert_eq!(got, want, "ssse3 c={c:#x} len={len}");
                    }
                    if is_x86_feature_detected!("avx2") {
                        let mut got = base.clone();
                        let done = unsafe { t.xor_mul_into_avx2(&mut got, &src) };
                        MulTable::xor_mul_scalar(&t.lo, &t.hi, &mut got[done..], &src[done * 2..]);
                        assert_eq!(got, want, "avx2 c={c:#x} len={len}");
                    }
                    if is_x86_feature_detected!("gfni") && is_x86_feature_detected!("avx2") {
                        let mut got = base.clone();
                        let done = unsafe { t.xor_mul_into_gfni(&mut got, &src) };
                        MulTable::xor_mul_scalar(&t.lo, &t.hi, &mut got[done..], &src[done * 2..]);
                        assert_eq!(got, want, "gfni c={c:#x} len={len}");
                    }
                }
            }
        }
    }
}
