#!/bin/sh
# Build the Linux distribution packages: nzbfast .deb (Debian, Ubuntu,
# Raspberry Pi OS) and .rpm (Fedora, RHEL, openSUSE), for amd64 and
# arm64, from binaries that are ALREADY BUILT.
#
#   packaging/linux/make-packages.sh                     # both arches, both formats
#   packaging/linux/make-packages.sh --arch amd64        # one arch
#   packaging/linux/make-packages.sh --format deb        # one format
#   packaging/linux/make-packages.sh --bin-amd64 path/to/nzbfast ...
#
# Output: packaging/linux/out/
#   nzbfast_<ver>-0beta<n>_amd64.deb    nzbfast-<ver>-0.beta<n>.x86_64.rpm
#   nzbfast_<ver>-0beta<n>_arm64.deb    nzbfast-<ver>-0.beta<n>.aarch64.rpm
#
# BETA is in the package version, not just the file name, and it is in
# the version in the way both package managers understand as "earlier
# than the real thing": dpkg reads the revision `0beta1` as less than
# `1`, rpm reads the release `0.beta1` as less than `1`. So the first
# non-beta package of the SAME upstream version still upgrades cleanly
# over one of these. Set NZBFAST_PKG_BETA=0 when that day comes.
#
# LINUX ONLY, and it says so rather than half-working: it needs dpkg-deb
# and rpmbuild. On Debian/Ubuntu that is `apt-get install dpkg-dev rpm`,
# on Fedora `dnf install rpm-build dpkg`. The release Mac cannot run it;
# CI does (.github/workflows/release.yml, job `packages`).
#
# The binaries it packages must be STATIC musl builds, for the same
# reason the release tarballs are (packaging/upload-release-assets.sh):
# a glibc build made on a current CI runner will not start on Debian 12,
# which is exactly the audience for a .deb. That is asserted here, not
# assumed - a .deb whose binary cannot execute is worse than no .deb.
set -eu

cd "$(dirname "$0")/../.."                      # repo root
ROOT=$(pwd)
PKGDIR=packaging/linux
OUTDIR="$ROOT/$PKGDIR/out"

VERSION=$(sed -n 's/^version = "\(.*\)"/\1/p' crates/nzbfast/Cargo.toml | head -1)
[ -n "$VERSION" ] || { echo "could not read version from crates/nzbfast/Cargo.toml" >&2; exit 1; }

BETA=${NZBFAST_PKG_BETA:-1}
PRINT_UNIT=0
ARCHES="amd64 arm64"
FORMATS="deb rpm"
BIN_AMD64=target/x86_64-unknown-linux-musl/release/nzbfast
BIN_ARM64=target/aarch64-unknown-linux-musl/release/nzbfast

while [ $# -gt 0 ]; do
    case "$1" in
        --arch)       ARCHES=$2; shift 2 ;;
        --format)     FORMATS=$2; shift 2 ;;
        --bin-amd64)  BIN_AMD64=$2; shift 2 ;;
        --bin-arm64)  BIN_ARM64=$2; shift 2 ;;
        --out)        OUTDIR=$2; shift 2 ;;
        # Print the unit the packages would install and stop. The one
        # part of this script that needs no packaging tools, so
        # packaging/tests can check the substitutions on any OS.
        --print-unit) PRINT_UNIT=1; shift ;;
        -h|--help)    sed -n '2,30p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 1 ;;
    esac
done

# `0beta1` / `0.beta1` sort BELOW a plain `1` in both package managers.
# NZBFAST_PKG_BETA=0 ships the release revision instead.
if [ "$BETA" = "0" ]; then
    DEB_REVISION=1
    RPM_RELEASE=1
else
    DEB_REVISION="0beta$BETA"
    RPM_RELEASE="0.beta$BETA"
fi
DEB_VERSION="$VERSION-$DEB_REVISION"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
mkdir -p "$OUTDIR"

# ---------------------------------------------------------------- the unit
# The service unit is NOT a second copy of packaging/systemd/nzbfast.service.
# It is that file, with the paths a distribution package has to use
# substituted in, and every substitution asserted: a sed that silently
# matches nothing would ship a unit pointing at /usr/local/bin (where a
# package must never install) or at a config path the package does not
# create, and systemd would report the failure long after the build.
make_unit() {
    src=packaging/systemd/nzbfast.service
    dst=$1
    # Everything above [Unit] in the source file is the by-hand install
    # recipe: copy a binary to /usr/local/bin, useradd, cp the config.
    # In a packaged unit that is not just noise, it is wrong - the
    # package did all of it, somewhere else - so the header is replaced
    # rather than carried.
    {
        echo '# nzbfast daemon - installed by the nzbfast .deb / .rpm package.'
        echo '#'
        echo '# Do not edit this file: the next package upgrade replaces it.'
        echo '# Port and folders live in /etc/nzbfast/nzbfast.env; anything'
        echo '# else belongs in a drop-in via `systemctl edit nzbfast`.'
        echo '#'
        echo '# Generated from packaging/systemd/nzbfast.service by'
        echo '# packaging/linux/make-packages.sh.'
        sed -n '/^\[Unit\]/,$p' "$src"
    } > "$dst"
    # from                              to
    subst='/usr/local/bin/nzbfast|/usr/bin/nzbfast
--config /etc/nzbfast/config.json|--config ${NZBFAST_CONFIG}
--port 6789|--port ${NZBFAST_PORT}
--out /var/lib/nzbfast/downloads|--out ${NZBFAST_OUT}
--watch /var/lib/nzbfast/watch|--watch ${NZBFAST_WATCH}
--index-db /var/lib/nzbfast/index.db|--index-db ${NZBFAST_INDEX_DB}'
    echo "$subst" | while IFS='|' read -r from to; do
        grep -qF -- "$from" "$dst" || {
            echo "make_unit: '$from' is not in $src any more." >&2
            echo "  The unit was edited without updating this list, so the" >&2
            echo "  packaged unit would keep a path the package does not use." >&2
            exit 1
        }
        # `|` cannot appear in either side (they are paths and flags), so
        # it is a safe sed delimiter here.
        sed -i.bak "s|$(printf '%s' "$from" | sed 's/[[\.*^$]/\\&/g')|$to|" "$dst"
        rm -f "$dst.bak"
    done || exit 1

    # The daemon's environment comes from the one file this package owns
    # under /etc. `-` on the path: a missing env file must not stop the
    # service, because the Environment= defaults below cover every value.
    # They are defaults, not overrides - systemd lets the file win.
    tmp="$dst.new"
    awk '
        { print }
        /^\[Service\]$/ && !done {
            print "EnvironmentFile=-/etc/nzbfast/nzbfast.env"
            print "Environment=NZBFAST_PORT=6789"
            print "Environment=NZBFAST_CONFIG=/var/lib/nzbfast/config.json"
            print "Environment=NZBFAST_OUT=/var/lib/nzbfast/downloads"
            print "Environment=NZBFAST_WATCH=/var/lib/nzbfast/watch"
            print "Environment=NZBFAST_INDEX_DB=/var/lib/nzbfast/index.db"
            done = 1
        }
    ' "$dst" > "$tmp" && mv "$tmp" "$dst"

    # Belt for the braces above: whatever the substitutions did, these two
    # must be true of the file that ships.
    grep -q '^EnvironmentFile=-/etc/nzbfast/nzbfast.env$' "$dst" || {
        echo "make_unit: [Service] section not found in $src." >&2; exit 1; }
    ! grep -q '/usr/local/' "$dst" || {
        echo "make_unit: the packaged unit still names /usr/local." >&2; exit 1; }
}

if [ "$PRINT_UNIT" = 1 ]; then
    make_unit "$WORK/nzbfast.service"
    cat "$WORK/nzbfast.service"
    exit 0
fi

# ------------------------------------------------------------- the payload
# Assert the binary is what the package claims: built for the target
# architecture, and statically linked so it starts on distributions older
# than the builder.
check_binary() {
    bin=$1; want_machine=$2
    [ -f "$bin" ] || {
        echo "missing binary: $bin" >&2
        echo "  Build it first:  cargo zigbuild --release -p nzbfast \\" >&2
        echo "                     --target x86_64-unknown-linux-musl \\" >&2
        echo "                     --target aarch64-unknown-linux-musl" >&2
        exit 1; }
    desc=$(file -b "$bin")
    case "$desc" in
        *"$want_machine"*) ;;
        *) echo "$bin is not a $want_machine binary: $desc" >&2; exit 1 ;;
    esac
    # musl builds report either spelling depending on whether the linker
    # produced a position-independent static executable.
    case "$desc" in
        *"statically linked"*|*"static-pie linked"*) ;;
        *) echo "$bin is NOT statically linked: $desc" >&2
           echo "  A glibc build made on a current runner does not start on" >&2
           echo "  Debian 12, which is most of this package's audience." >&2
           exit 1 ;;
    esac
}

# --------------------------------------------------------------- the stage
# One file tree per architecture, used by BOTH package formats, so a
# difference between the .deb and the .rpm can only come from the package
# metadata - never from a file that is in one and not the other.
stage_tree() {
    bin=$1; stage=$2
    install -D -m 0755 "$bin"                             "$stage/usr/bin/nzbfast"
    make_unit "$WORK/nzbfast.service"
    install -D -m 0644 "$WORK/nzbfast.service"            "$stage/usr/lib/systemd/system/nzbfast.service"
    install -D -m 0644 $PKGDIR/nzbfast.env                "$stage/etc/nzbfast/nzbfast.env"
    install -D -m 0644 packaging/config.example.json      "$stage/usr/share/nzbfast/config.example.json"
    install -D -m 0755 $PKGDIR/setup-data-dir.sh          "$stage/usr/share/nzbfast/setup-data-dir.sh"
    install -D -m 0644 $PKGDIR/deb/copyright              "$stage/usr/share/doc/nzbfast/copyright"
    install -D -m 0644 $PKGDIR/README.md                  "$stage/usr/share/doc/nzbfast/README.linux-packages.md"
    # No path under /var/lib/nzbfast is staged. See setup-data-dir.sh:
    # the package owning nothing in the data directory is what makes an
    # upgrade unable to touch settings.json.
}

build_deb() {
    stage=$1; debarch=$2
    d="$WORK/deb-$debarch"
    rm -rf "$d"; cp -a "$stage" "$d"
    mkdir -p "$d/DEBIAN"
    size=$(du -sk "$d" | cut -f1)
    sed -e "s|@@VERSION@@|$DEB_VERSION|" \
        -e "s|@@ARCH@@|$debarch|" \
        -e "s|@@INSTALLED_SIZE@@|$size|" \
        $PKGDIR/deb/control.in > "$d/DEBIAN/control"
    # The env file is the only conffile. Everything else the package owns
    # is program, unit or documentation, and everything the DAEMON writes
    # is outside the package entirely.
    echo /etc/nzbfast/nzbfast.env > "$d/DEBIAN/conffiles"
    for s in postinst prerm postrm; do
        install -m 0755 "$PKGDIR/deb/$s" "$d/DEBIAN/$s"
    done
    ( cd "$d" && find . -path ./DEBIAN -prune -o -type f -print \
        | sed 's|^\./||' | LC_ALL=C sort | xargs -r md5sum > DEBIAN/md5sums )
    out="$OUTDIR/nzbfast_${DEB_VERSION}_${debarch}.deb"
    # --root-owner-group: every file root:root without needing fakeroot.
    # -Zgzip: not the default (xz) on purpose. The release asset scanner
    # has to open this package on the release Mac, whose tools read gzip
    # everywhere and xz only sometimes, and a gate that cannot look
    # inside an asset refuses the whole release.
    dpkg-deb --root-owner-group -Zgzip --build "$d" "$out" >/dev/null
    echo "$out"
}

build_rpm() {
    stage=$1; rpmarch=$2
    spec="$WORK/nzbfast-$rpmarch.spec"
    sed -e "s|@@VERSION@@|$VERSION|g" \
        -e "s|@@RELEASE@@|$RPM_RELEASE|g" \
        -e "s|@@RPMDATE@@|$(date -u +'%a %b %d %Y')|g" \
        $PKGDIR/rpm/nzbfast.spec.in > "$spec"
    top="$WORK/rpmbuild-$rpmarch"
    mkdir -p "$top"
    rpmbuild -bb "$spec" \
        --target "$rpmarch" \
        --quiet \
        --define "_topdir $top" \
        --define "_stagedir $stage" \
        --define "_sourcedir $WORK" \
        --define "_builddir $WORK" \
        >/dev/null
    built=$(find "$top/RPMS" -name '*.rpm' -type f | head -1)
    [ -n "$built" ] || { echo "rpmbuild produced no package for $rpmarch" >&2; exit 1; }
    out="$OUTDIR/$(basename "$built")"
    mv "$built" "$out"
    echo "$out"
}

case " $FORMATS " in
    *deb*) command -v dpkg-deb >/dev/null 2>&1 || {
        echo "dpkg-deb is not installed (apt-get install dpkg-dev)." >&2; exit 1; } ;;
esac
case " $FORMATS " in
    *rpm*) command -v rpmbuild >/dev/null 2>&1 || {
        echo "rpmbuild is not installed (apt-get install rpm / dnf install rpm-build)." >&2; exit 1; } ;;
esac
# The linkage assertion below is the reason this is a hard requirement
# and not a "check it if we can": the one thing that must not happen is
# publishing a package whose binary the target distro cannot execute, and
# a skipped check reports success just as loudly as a passed one.
command -v file >/dev/null 2>&1 || {
    echo "the 'file' command is not installed, and it is what proves the" >&2
    echo "packaged binary is static and built for the right architecture." >&2
    echo "apt-get install file / dnf install file" >&2; exit 1; }

built=""
for arch in $ARCHES; do
    case "$arch" in
        amd64|x86_64)  bin=$BIN_AMD64; debarch=amd64; rpmarch=x86_64;  machine="x86-64" ;;
        arm64|aarch64) bin=$BIN_ARM64; debarch=arm64; rpmarch=aarch64; machine="aarch64" ;;
        *) echo "unknown architecture: $arch (use amd64 or arm64)" >&2; exit 1 ;;
    esac
    check_binary "$bin" "$machine"
    stage="$WORK/stage-$debarch"
    stage_tree "$bin" "$stage"
    for fmt in $FORMATS; do
        case "$fmt" in
            deb) built="$built $(build_deb "$stage" "$debarch")" ;;
            rpm) built="$built $(build_rpm "$stage" "$rpmarch")" ;;
            *) echo "unknown format: $fmt (use deb or rpm)" >&2; exit 1 ;;
        esac
    done
done

echo
echo "BETA packages in $OUTDIR:"
for f in $built; do
    printf '  %-52s %6s KiB\n' "$(basename "$f")" "$(du -k "$f" | cut -f1)"
done
echo
echo "These are NOT in the signed update manifest (packaging/make-latest-json.sh)"
echo "and must not be added to it until the install and upgrade paths have been"
echo "tested on both distro families - the manifest carries an anti-rollback"
echo "serial and signed payloads."
