# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: nzbfast.nzbfast
PackageVersion: 1.1.3
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2026-08-16
AppsAndFeaturesEntries:
- DisplayName: nzbfast
  Publisher: nzbfast
  DisplayVersion: 1.1.3
  ProductCode: '{72B5B673-54D7-46ED-BDDC-C7D3E571D242}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nzbfast/nzbfast/releases/download/v1.1.3/nzbfast-1.1.3-windows-x64-setup.exe
  InstallerSha256: DEB0B5D8FB3962811ABFBC1DAA21B3DDBF5C0F16F7E1FD074F51F23B5AC76762
ManifestType: installer
ManifestVersion: 1.12.0
